// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.keyboardevent.keypress.hack.use_legacy_keycode_and_charcode", "powerpoint.officeapps.live.com");
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "fe544d3a-aeed-409f-b4b3-2f1ae4785fec");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1553669403);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1553669523);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1553710220);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1553696060);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1553695940);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1553669283);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1553670741);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1553669643);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1553668894);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7c89cd0d-ff8f-4a74-8589-79e9dacdafcd}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1553619600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553710467257");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553712275257");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1553711685024");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1553715285024");
user_pref("browser.search.region", "RU");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1553697108");
user_pref("browser.slowStartup.averageTime", 8986);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190322095656");
user_pref("browser.startup.homepage_override.mstone", "66.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1553671739560");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "d635fd8942d541489f91403861889bb1");
user_pref("extensions.blocklist.lastModified", "Tue, 26 Mar 2019 17:13:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1553669404);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190322095656");
user_pref("extensions.lastAppVersion", "66.0.1");
user_pref("extensions.lastPlatformVersion", "66.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0eff846c-566d-4d13-b9b1-f369b31ee211\",\"screenshots@mozilla.org\":\"4700c703-6b65-4df1-9016-d439f858d5a4\",\"webcompat-reporter@mozilla.org\":\"3a8a77e5-e198-426b-914a-3e03a3069173\",\"webcompat@mozilla.org\":\"ad51983d-bf3d-40bf-8f4f-bf85115cbec1\",\"fxmonitor@mozilla.org\":\"370bf0bf-9f78-4b82-8a48-a2806d214357\"}");
user_pref("idle.lastDailyNotification", 1553672728);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 180);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1553669076);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190322095656");
user_pref("media.gmp-manager.lastCheck", 1553671750);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1553672728);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "d13b18f4-e70a-40ad-af6f-dd21ea02b376");
user_pref("security.sandbox.plugin.tempDirSuffix", "c4c6fdfc-8940-489d-abc2-524526824d89");
user_pref("services.blocklist.addons.checked", 1553707128);
user_pref("services.blocklist.gfx.checked", 1553707128);
user_pref("services.blocklist.onecrl.checked", 1553707128);
user_pref("services.blocklist.pinning.checked", 1553707128);
user_pref("services.blocklist.plugins.checked", 1553707128);
user_pref("services.settings.clock_skew_seconds", -127);
user_pref("services.settings.last_etag", "\"1553706908694\"");
user_pref("services.settings.last_update_seconds", 1553707555);
user_pref("services.settings.main.language-dictionaries.last_check", 1553707128);
user_pref("services.settings.main.onboarding.last_check", 1553707128);
user_pref("services.settings.main.sites-classification.last_check", 1553707128);
user_pref("services.settings.main.tippytop.last_check", 1553707128);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1553672728);
user_pref("toolkit.startup.last_success", 1553697098);
user_pref("toolkit.telemetry.cachedClientID", "a18f003b-fa6b-4a75-8470-164b5d06a343");
user_pref("toolkit.telemetry.previousBuildID", "20190322095656");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
